"""
Polymarket market data for weather temperature markets.

Loads markets from weather_markets.json (generated by update_bot),
fetches live prices via Gamma API events endpoint.
"""

import json
import re
import ssl
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

_ctx = ssl.create_default_context()

GAMMA_API = "https://gamma-api.polymarket.com"


@dataclass
class WeatherMarket:
    """Parsed weather temperature market from Polymarket."""
    event_slug: str           # "highest-temperature-in-chicago-on-march-7"
    market_slug: str          # "will-the-highest-temperature-in-chicago-be-44-45-f-on-march-7"
    question: str
    city: str                 # "chicago"
    date: str                 # "2026-03-07"
    unit: str                 # "F" or "C"
    bucket_lower: Optional[float]  # None = open-ended low
    bucket_upper: Optional[float]  # None = open-ended high (exclusive)
    bucket_label: str         # "44-45°F"
    yes_price: float = 0.0
    no_price: float = 0.0
    condition_id: str = ""
    yes_token_id: str = ""
    no_token_id: str = ""
    end_date: str = ""
    active: bool = True

    @property
    def days_remaining(self) -> float:
        if not self.end_date:
            return 0.0
        try:
            if "T" in self.end_date:
                end_dt = datetime.fromisoformat(self.end_date.replace("Z", "+00:00"))
            else:
                end_dt = datetime.strptime(self.end_date, "%Y-%m-%d").replace(
                    hour=23, minute=59, second=59, tzinfo=timezone.utc
                )
            now = datetime.now(timezone.utc)
            delta = end_dt - now
            return max(0, delta.total_seconds() / 86400)
        except Exception:
            return 0.0

    @property
    def hours_remaining(self) -> float:
        return self.days_remaining * 24

    @property
    def is_resolved(self) -> bool:
        """Bucket is effectively resolved (price at 0% or 100%)."""
        return self.yes_price < 0.01 or self.yes_price > 0.99


class WeatherPolymarketData:
    """Manages weather market data from Polymarket."""

    def __init__(self, markets_json: Path):
        self._markets_json = markets_json
        self._markets: List[WeatherMarket] = []
        self._all_markets_map: Dict[str, WeatherMarket] = {}  # includes expired

    @property
    def markets(self) -> List[WeatherMarket]:
        return self._markets

    def update_from_json(self) -> bool:
        """Load markets from weather_markets.json."""
        if not self._markets_json.exists():
            return False

        try:
            with open(self._markets_json) as f:
                data = json.load(f)
        except Exception:
            return False

        now = datetime.now(timezone.utc)
        markets = []
        all_map: Dict[str, WeatherMarket] = {}
        for entry in data:
            end_str = entry.get("end_date", "")
            expired = False
            try:
                if "T" in end_str:
                    end_dt = datetime.fromisoformat(end_str.replace("Z", "+00:00"))
                else:
                    end_dt = datetime.strptime(end_str, "%Y-%m-%d").replace(
                        hour=23, minute=59, second=59, tzinfo=timezone.utc
                    )
                if end_dt < now:
                    expired = True
            except (ValueError, TypeError):
                pass

            wm = WeatherMarket(
                event_slug=entry.get("event_slug", ""),
                market_slug=entry.get("market_slug", ""),
                question=entry.get("question", ""),
                city=entry.get("city", ""),
                date=entry.get("date", ""),
                unit=entry.get("unit", "F"),
                bucket_lower=entry.get("bucket_lower"),
                bucket_upper=entry.get("bucket_upper"),
                bucket_label=entry.get("bucket_label", ""),
                condition_id=entry.get("condition_id", ""),
                yes_token_id=entry.get("yes_token_id", ""),
                no_token_id=entry.get("no_token_id", ""),
                end_date=end_str,
            )
            all_map[wm.market_slug] = wm
            if not expired:
                markets.append(wm)

        self._markets = markets
        self._all_markets_map = all_map
        return True

    def refresh_prices(self) -> int:
        """Fetch live prices for all loaded markets via Gamma API.

        Searches events by slug, extracts outcomePrices for each sub-market.
        Returns number of markets updated.
        """
        if not self._markets:
            return 0

        # Group markets by event_slug
        event_slugs = set(m.event_slug for m in self._markets)

        # Fetch prices per event
        slug_prices: Dict[str, Tuple[float, float]] = {}  # condition_id -> (yes, no)

        for event_slug in event_slugs:
            try:
                url = f"{GAMMA_API}/events?slug={event_slug}"
                req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
                resp = urllib.request.urlopen(req, timeout=10, context=_ctx)
                data = json.loads(resp.read())
                if not data:
                    continue

                for mkt in data[0].get("markets", []):
                    cid = mkt.get("conditionId", "")
                    if not cid:
                        continue
                    try:
                        prices = json.loads(mkt.get("outcomePrices", "[]"))
                        yes_p = float(prices[0])
                        no_p = float(prices[1]) if len(prices) > 1 else 1 - yes_p
                        slug_prices[cid] = (yes_p, no_p)
                    except Exception:
                        continue
            except Exception:
                continue

        # Update markets
        updated = 0
        for m in self._markets:
            if m.condition_id in slug_prices:
                m.yes_price, m.no_price = slug_prices[m.condition_id]
                m.active = True
                updated += 1
            elif m.days_remaining <= 0:
                m.active = False

        return updated

    def refresh_prices_batch(self) -> int:
        """Batch price refresh via paginated events search.

        Faster than per-event queries when we have many events.
        Searches for "highest temperature" in all open events.
        """
        slug_prices: Dict[str, Tuple[float, float]] = {}
        offset = 0

        while True:
            try:
                url = f"{GAMMA_API}/events?closed=false&limit=100&offset={offset}"
                req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
                resp = urllib.request.urlopen(req, timeout=15, context=_ctx)
                data = json.loads(resp.read())
            except Exception:
                break

            if not data:
                break

            for ev in data:
                title = ev.get("title", "").lower()
                if "highest temperature" not in title:
                    continue

                for mkt in ev.get("markets", []):
                    cid = mkt.get("conditionId", "")
                    if not cid:
                        continue
                    try:
                        prices = json.loads(mkt.get("outcomePrices", "[]"))
                        yes_p = float(prices[0])
                        no_p = float(prices[1]) if len(prices) > 1 else 1 - yes_p
                        slug_prices[cid] = (yes_p, no_p)
                    except Exception:
                        continue

            offset += 100
            if len(data) < 100:
                break

        # Update markets
        updated = 0
        for m in self._markets:
            if m.condition_id in slug_prices:
                m.yes_price, m.no_price = slug_prices[m.condition_id]
                m.active = True
                updated += 1
            elif m.days_remaining <= 0:
                m.active = False

        return updated

    def update(self) -> bool:
        """Load from JSON + refresh prices."""
        ok = self.update_from_json()
        if ok:
            self.refresh_prices_batch()
        return ok

    @staticmethod
    def get_orderbook(token_id: str) -> dict:
        """Fetch orderbook from CLOB API."""
        try:
            url = f"https://clob.polymarket.com/book?token_id={token_id}"
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            resp = urllib.request.urlopen(req, timeout=10, context=_ctx)
            return json.loads(resp.read())
        except Exception:
            return {"asks": [], "bids": []}

    @staticmethod
    def get_usable_liquidity(token_id: str, fair_price: float) -> Tuple[float, float, float]:
        """Get available liquidity at ask prices below fair price.

        Returns (best_ask, usable_liquidity_usd, weighted_price).
        """
        try:
            ob = WeatherPolymarketData.get_orderbook(token_id)
            asks = ob.get("asks", [])
            if not asks:
                return 0.0, 0.0, 0.0

            best_ask = min(float(a["price"]) for a in asks)
            total_size = 0.0
            total_cost = 0.0
            for a in asks:
                price = float(a["price"])
                size = float(a["size"])
                if price <= fair_price:
                    cost = price * size
                    total_size += size
                    total_cost += cost

            weighted_price = total_cost / total_size if total_size > 0 else best_ask
            return best_ask, total_cost, weighted_price
        except Exception:
            return 0.0, 0.0, 0.0

    def get_active_markets(self) -> List[WeatherMarket]:
        """Get non-resolved, non-expired active markets."""
        return [
            m for m in self._markets
            if m.active and not m.is_resolved and m.days_remaining > 0
        ]

    def get_markets_by_city(self, city: str) -> List[WeatherMarket]:
        return [m for m in self._markets if m.city == city and m.active]

    def get_markets_by_event(self, event_slug: str) -> List[WeatherMarket]:
        return [m for m in self._markets if m.event_slug == event_slug and m.active]
